default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: postgres
  password: password
  host: <%= ENV.fetch('DATABASE_URL', '127.0.0.1') %>

development:
  <<: *default
  database: twitter_keiba_devlopment

test:
  <<: *default
  database: twitter_keiba_test

production:
  <<: *default
  database: twitter_keiba_production