defaults: &defaults
  color: ['white', 'black', 'red', 'blue', 'yellow', 'green', 'orange', 'pink']
  index:
    5: [0, 1, 2, 3, 4]
    6: [0, 1, 2, 3, 4, 5]
    7: [0, 1, 2, 3, 4, 5, 6]
    8: [0, 1, 2, 3, 4, 5, 6, 7]
    9: [0, 1, 2, 3, 4, 5, 6, 7, 7]
    10: [0, 1, 2, 3, 4, 5, 6, 6, 7, 7]
    11: [0, 1, 2, 3, 4, 5, 5, 6, 6, 7, 7]
    12: [0, 1, 2, 3, 4, 4, 5, 5, 6, 6, 7, 7]
    13: [0, 1, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7]
    14: [0, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7]
    15: [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7]
    16: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7]
    17: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 7]
    18: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7]

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults